#!/usr/bin/env bash
#
# @(#) start-server
#
# This script starts the Twitter Aggregator app.
#
pgm=${0##*/}

# Clean out prior tweets directory.
find ./public/tweets/ -type f -name '*.html' -maxdepth 1 -delete

# Run Twitter Aggregator
env NODE_ENV=development node ./app.js
